"""autogenerated by genmsg_py from FollowTrajectoryAction.msg. Do not edit."""
import roslib.message
import struct

import roslib.rostime
import actionlib_msgs.msg
import geometry_msgs.msg
import seabee3_msgs.msg
import seabee3_actions.msg
import std_msgs.msg

class FollowTrajectoryAction(roslib.message.Message):
  _md5sum = "d086d8ba0ef13f85597f1951df1815cd"
  _type = "seabee3_actions/FollowTrajectoryAction"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

FollowTrajectoryActionGoal action_goal
FollowTrajectoryActionResult action_result
FollowTrajectoryActionFeedback action_feedback

================================================================================
MSG: seabee3_actions/FollowTrajectoryActionGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
FollowTrajectoryGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: seabee3_actions/FollowTrajectoryGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal

# the target trajectory
seabee3_msgs/Trajectory trajectory

================================================================================
MSG: seabee3_msgs/Trajectory
Header header
# the discrete intervals that make up this trajectory
seabee3_msgs/TrajectoryInterval[] intervals

================================================================================
MSG: seabee3_msgs/TrajectoryInterval
duration length
seabee3_msgs/TrajectoryWaypoint initial_state
geometry_msgs/TwistWithCovariance acceleration

================================================================================
MSG: seabee3_msgs/TrajectoryWaypoint
# pose
geometry_msgs/PoseWithCovariance pose

# velocity
geometry_msgs/TwistWithCovariance velocity

================================================================================
MSG: geometry_msgs/PoseWithCovariance
# This represents a pose in free space with uncertainty.

Pose pose

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistWithCovariance
# This expresses velocity in free space with uncertianty.

Twist twist

# Row-major representation of the 6x6 covariance matrix
# The orientation parameters use a fixed-axis representation.
# In order, the parameters are:
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
float64[36] covariance

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into it's linear and angular parts. 
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
================================================================================
MSG: seabee3_actions/FollowTrajectoryActionResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FollowTrajectoryResult result

================================================================================
MSG: actionlib_msgs/GoalStatus
GoalID goal_id
uint8 status
uint8 PENDING         = 0   # The goal has yet to be processed by the action server
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                            #   and has since completed its execution (Terminal State)
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                            #    to some failure (Terminal State)
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                            #    because the goal was unattainable or invalid (Terminal State)
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                            #    and has not yet completed execution
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                            #    but the action server has not yet confirmed that the goal is canceled
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                            #    and was successfully cancelled (Terminal State)
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                            #    sent over the wire by an action server

#Allow for the user to associate a string with GoalStatus for debugging
string text


================================================================================
MSG: seabee3_actions/FollowTrajectoryResult
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# result

# the ending state
seabee3_msgs/TrajectoryWaypoint final_waypoint

================================================================================
MSG: seabee3_actions/FollowTrajectoryActionFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
FollowTrajectoryFeedback feedback

================================================================================
MSG: seabee3_actions/FollowTrajectoryFeedback
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# feedback

# the interval we're trying to achieve
seabee3_msgs/TrajectoryInterval target_interval

# where we thought we'd be at this point in the interval
seabee3_msgs/TrajectoryWaypoint expected_state

# where we actually are
seabee3_msgs/TrajectoryWaypoint current_state


"""
  __slots__ = ['action_goal','action_result','action_feedback']
  _slot_types = ['seabee3_actions/FollowTrajectoryActionGoal','seabee3_actions/FollowTrajectoryActionResult','seabee3_actions/FollowTrajectoryActionFeedback']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       action_goal,action_result,action_feedback
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(FollowTrajectoryAction, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.action_goal is None:
        self.action_goal = seabee3_actions.msg.FollowTrajectoryActionGoal()
      if self.action_result is None:
        self.action_result = seabee3_actions.msg.FollowTrajectoryActionResult()
      if self.action_feedback is None:
        self.action_feedback = seabee3_actions.msg.FollowTrajectoryActionFeedback()
    else:
      self.action_goal = seabee3_actions.msg.FollowTrajectoryActionGoal()
      self.action_result = seabee3_actions.msg.FollowTrajectoryActionResult()
      self.action_feedback = seabee3_actions.msg.FollowTrajectoryActionFeedback()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs))
      _x = self.action_goal.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs))
      _x = self.action_goal.goal_id.id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.action_goal.goal.trajectory.header.seq, _x.action_goal.goal.trajectory.header.stamp.secs, _x.action_goal.goal.trajectory.header.stamp.nsecs))
      _x = self.action_goal.goal.trajectory.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.action_goal.goal.trajectory.intervals)
      buff.write(_struct_I.pack(length))
      for val1 in self.action_goal.goal.trajectory.intervals:
        _v1 = val1.length
        _x = _v1
        buff.write(_struct_2i.pack(_x.secs, _x.nsecs))
        _v2 = val1.initial_state
        _v3 = _v2.pose
        _v4 = _v3.pose
        _v5 = _v4.position
        _x = _v5
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v6 = _v4.orientation
        _x = _v6
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.z, _x.w))
        buff.write(_struct_36d.pack(*_v3.covariance))
        _v7 = _v2.velocity
        _v8 = _v7.twist
        _v9 = _v8.linear
        _x = _v9
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v10 = _v8.angular
        _x = _v10
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        buff.write(_struct_36d.pack(*_v7.covariance))
        _v11 = val1.acceleration
        _v12 = _v11.twist
        _v13 = _v12.linear
        _x = _v13
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v14 = _v12.angular
        _x = _v14
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        buff.write(_struct_36d.pack(*_v11.covariance))
      _x = self
      buff.write(_struct_3I.pack(_x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs))
      _x = self.action_result.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs))
      _x = self.action_result.status.goal_id.id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.action_result.status.status))
      _x = self.action_result.status.text
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.action_result.result.final_waypoint.pose.pose.position.x, _x.action_result.result.final_waypoint.pose.pose.position.y, _x.action_result.result.final_waypoint.pose.pose.position.z, _x.action_result.result.final_waypoint.pose.pose.orientation.x, _x.action_result.result.final_waypoint.pose.pose.orientation.y, _x.action_result.result.final_waypoint.pose.pose.orientation.z, _x.action_result.result.final_waypoint.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.action_result.result.final_waypoint.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.action_result.result.final_waypoint.velocity.twist.linear.x, _x.action_result.result.final_waypoint.velocity.twist.linear.y, _x.action_result.result.final_waypoint.velocity.twist.linear.z, _x.action_result.result.final_waypoint.velocity.twist.angular.x, _x.action_result.result.final_waypoint.velocity.twist.angular.y, _x.action_result.result.final_waypoint.velocity.twist.angular.z))
      buff.write(_struct_36d.pack(*self.action_result.result.final_waypoint.velocity.covariance))
      _x = self
      buff.write(_struct_3I.pack(_x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs))
      _x = self.action_feedback.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs))
      _x = self.action_feedback.status.goal_id.id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.action_feedback.status.status))
      _x = self.action_feedback.status.text
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i7d.pack(_x.action_feedback.feedback.target_interval.length.secs, _x.action_feedback.feedback.target_interval.length.nsecs, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.target_interval.initial_state.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.z, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.z))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.target_interval.initial_state.velocity.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.target_interval.acceleration.twist.linear.x, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.y, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.z, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.x, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.y, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.z))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.target_interval.acceleration.covariance))
      _x = self
      buff.write(_struct_7d.pack(_x.action_feedback.feedback.expected_state.pose.pose.position.x, _x.action_feedback.feedback.expected_state.pose.pose.position.y, _x.action_feedback.feedback.expected_state.pose.pose.position.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.x, _x.action_feedback.feedback.expected_state.pose.pose.orientation.y, _x.action_feedback.feedback.expected_state.pose.pose.orientation.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.expected_state.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.expected_state.velocity.twist.linear.x, _x.action_feedback.feedback.expected_state.velocity.twist.linear.y, _x.action_feedback.feedback.expected_state.velocity.twist.linear.z, _x.action_feedback.feedback.expected_state.velocity.twist.angular.x, _x.action_feedback.feedback.expected_state.velocity.twist.angular.y, _x.action_feedback.feedback.expected_state.velocity.twist.angular.z))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.expected_state.velocity.covariance))
      _x = self
      buff.write(_struct_7d.pack(_x.action_feedback.feedback.current_state.pose.pose.position.x, _x.action_feedback.feedback.current_state.pose.pose.position.y, _x.action_feedback.feedback.current_state.pose.pose.position.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.x, _x.action_feedback.feedback.current_state.pose.pose.orientation.y, _x.action_feedback.feedback.current_state.pose.pose.orientation.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.w))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.current_state.pose.covariance))
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.current_state.velocity.twist.linear.x, _x.action_feedback.feedback.current_state.velocity.twist.linear.y, _x.action_feedback.feedback.current_state.velocity.twist.linear.z, _x.action_feedback.feedback.current_state.velocity.twist.angular.x, _x.action_feedback.feedback.current_state.velocity.twist.angular.y, _x.action_feedback.feedback.current_state.velocity.twist.angular.z))
      buff.write(_struct_36d.pack(*self.action_feedback.feedback.current_state.velocity.covariance))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.action_goal is None:
        self.action_goal = seabee3_actions.msg.FollowTrajectoryActionGoal()
      if self.action_result is None:
        self.action_result = seabee3_actions.msg.FollowTrajectoryActionResult()
      if self.action_feedback is None:
        self.action_feedback = seabee3_actions.msg.FollowTrajectoryActionFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_goal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_goal.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.action_goal.goal.trajectory.header.seq, _x.action_goal.goal.trajectory.header.stamp.secs, _x.action_goal.goal.trajectory.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_goal.goal.trajectory.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.action_goal.goal.trajectory.intervals = []
      for i in range(0, length):
        val1 = seabee3_msgs.msg.TrajectoryInterval()
        _v15 = val1.length
        _x = _v15
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2i.unpack(str[start:end])
        _v16 = val1.initial_state
        _v17 = _v16.pose
        _v18 = _v17.pose
        _v19 = _v18.position
        _x = _v19
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v20 = _v18.orientation
        _x = _v20
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _struct_4d.unpack(str[start:end])
        start = end
        end += 288
        _v17.covariance = _struct_36d.unpack(str[start:end])
        _v21 = _v16.velocity
        _v22 = _v21.twist
        _v23 = _v22.linear
        _x = _v23
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v24 = _v22.angular
        _x = _v24
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        start = end
        end += 288
        _v21.covariance = _struct_36d.unpack(str[start:end])
        _v25 = val1.acceleration
        _v26 = _v25.twist
        _v27 = _v26.linear
        _x = _v27
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v28 = _v26.angular
        _x = _v28
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        start = end
        end += 288
        _v25.covariance = _struct_36d.unpack(str[start:end])
        self.action_goal.goal.trajectory.intervals.append(val1)
      _x = self
      start = end
      end += 12
      (_x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_result.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_result.status.status,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_result.status.text = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.action_result.result.final_waypoint.pose.pose.position.x, _x.action_result.result.final_waypoint.pose.pose.position.y, _x.action_result.result.final_waypoint.pose.pose.position.z, _x.action_result.result.final_waypoint.pose.pose.orientation.x, _x.action_result.result.final_waypoint.pose.pose.orientation.y, _x.action_result.result.final_waypoint.pose.pose.orientation.z, _x.action_result.result.final_waypoint.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_result.result.final_waypoint.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.action_result.result.final_waypoint.velocity.twist.linear.x, _x.action_result.result.final_waypoint.velocity.twist.linear.y, _x.action_result.result.final_waypoint.velocity.twist.linear.z, _x.action_result.result.final_waypoint.velocity.twist.angular.x, _x.action_result.result.final_waypoint.velocity.twist.angular.y, _x.action_result.result.final_waypoint.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_result.result.final_waypoint.velocity.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_feedback.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_feedback.status.status,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_feedback.status.text = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.action_feedback.feedback.target_interval.length.secs, _x.action_feedback.feedback.target_interval.length.nsecs, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.w,) = _struct_2i7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.target_interval.initial_state.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.z, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.target_interval.initial_state.velocity.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.target_interval.acceleration.twist.linear.x, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.y, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.z, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.x, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.y, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.target_interval.acceleration.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 56
      (_x.action_feedback.feedback.expected_state.pose.pose.position.x, _x.action_feedback.feedback.expected_state.pose.pose.position.y, _x.action_feedback.feedback.expected_state.pose.pose.position.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.x, _x.action_feedback.feedback.expected_state.pose.pose.orientation.y, _x.action_feedback.feedback.expected_state.pose.pose.orientation.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.expected_state.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.expected_state.velocity.twist.linear.x, _x.action_feedback.feedback.expected_state.velocity.twist.linear.y, _x.action_feedback.feedback.expected_state.velocity.twist.linear.z, _x.action_feedback.feedback.expected_state.velocity.twist.angular.x, _x.action_feedback.feedback.expected_state.velocity.twist.angular.y, _x.action_feedback.feedback.expected_state.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.expected_state.velocity.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 56
      (_x.action_feedback.feedback.current_state.pose.pose.position.x, _x.action_feedback.feedback.current_state.pose.pose.position.y, _x.action_feedback.feedback.current_state.pose.pose.position.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.x, _x.action_feedback.feedback.current_state.pose.pose.orientation.y, _x.action_feedback.feedback.current_state.pose.pose.orientation.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.current_state.pose.covariance = _struct_36d.unpack(str[start:end])
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.current_state.velocity.twist.linear.x, _x.action_feedback.feedback.current_state.velocity.twist.linear.y, _x.action_feedback.feedback.current_state.velocity.twist.linear.z, _x.action_feedback.feedback.current_state.velocity.twist.angular.x, _x.action_feedback.feedback.current_state.velocity.twist.angular.y, _x.action_feedback.feedback.current_state.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.current_state.velocity.covariance = _struct_36d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs))
      _x = self.action_goal.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs))
      _x = self.action_goal.goal_id.id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.action_goal.goal.trajectory.header.seq, _x.action_goal.goal.trajectory.header.stamp.secs, _x.action_goal.goal.trajectory.header.stamp.nsecs))
      _x = self.action_goal.goal.trajectory.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.action_goal.goal.trajectory.intervals)
      buff.write(_struct_I.pack(length))
      for val1 in self.action_goal.goal.trajectory.intervals:
        _v29 = val1.length
        _x = _v29
        buff.write(_struct_2i.pack(_x.secs, _x.nsecs))
        _v30 = val1.initial_state
        _v31 = _v30.pose
        _v32 = _v31.pose
        _v33 = _v32.position
        _x = _v33
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v34 = _v32.orientation
        _x = _v34
        buff.write(_struct_4d.pack(_x.x, _x.y, _x.z, _x.w))
        buff.write(_v31.covariance.tostring())
        _v35 = _v30.velocity
        _v36 = _v35.twist
        _v37 = _v36.linear
        _x = _v37
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v38 = _v36.angular
        _x = _v38
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        buff.write(_v35.covariance.tostring())
        _v39 = val1.acceleration
        _v40 = _v39.twist
        _v41 = _v40.linear
        _x = _v41
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        _v42 = _v40.angular
        _x = _v42
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.z))
        buff.write(_v39.covariance.tostring())
      _x = self
      buff.write(_struct_3I.pack(_x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs))
      _x = self.action_result.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs))
      _x = self.action_result.status.goal_id.id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.action_result.status.status))
      _x = self.action_result.status.text
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d.pack(_x.action_result.result.final_waypoint.pose.pose.position.x, _x.action_result.result.final_waypoint.pose.pose.position.y, _x.action_result.result.final_waypoint.pose.pose.position.z, _x.action_result.result.final_waypoint.pose.pose.orientation.x, _x.action_result.result.final_waypoint.pose.pose.orientation.y, _x.action_result.result.final_waypoint.pose.pose.orientation.z, _x.action_result.result.final_waypoint.pose.pose.orientation.w))
      buff.write(self.action_result.result.final_waypoint.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.action_result.result.final_waypoint.velocity.twist.linear.x, _x.action_result.result.final_waypoint.velocity.twist.linear.y, _x.action_result.result.final_waypoint.velocity.twist.linear.z, _x.action_result.result.final_waypoint.velocity.twist.angular.x, _x.action_result.result.final_waypoint.velocity.twist.angular.y, _x.action_result.result.final_waypoint.velocity.twist.angular.z))
      buff.write(self.action_result.result.final_waypoint.velocity.covariance.tostring())
      _x = self
      buff.write(_struct_3I.pack(_x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs))
      _x = self.action_feedback.header.frame_id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs))
      _x = self.action_feedback.status.goal_id.id
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_B.pack(self.action_feedback.status.status))
      _x = self.action_feedback.status.text
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i7d.pack(_x.action_feedback.feedback.target_interval.length.secs, _x.action_feedback.feedback.target_interval.length.nsecs, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.w))
      buff.write(self.action_feedback.feedback.target_interval.initial_state.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.z, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.z))
      buff.write(self.action_feedback.feedback.target_interval.initial_state.velocity.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.target_interval.acceleration.twist.linear.x, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.y, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.z, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.x, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.y, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.z))
      buff.write(self.action_feedback.feedback.target_interval.acceleration.covariance.tostring())
      _x = self
      buff.write(_struct_7d.pack(_x.action_feedback.feedback.expected_state.pose.pose.position.x, _x.action_feedback.feedback.expected_state.pose.pose.position.y, _x.action_feedback.feedback.expected_state.pose.pose.position.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.x, _x.action_feedback.feedback.expected_state.pose.pose.orientation.y, _x.action_feedback.feedback.expected_state.pose.pose.orientation.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.w))
      buff.write(self.action_feedback.feedback.expected_state.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.expected_state.velocity.twist.linear.x, _x.action_feedback.feedback.expected_state.velocity.twist.linear.y, _x.action_feedback.feedback.expected_state.velocity.twist.linear.z, _x.action_feedback.feedback.expected_state.velocity.twist.angular.x, _x.action_feedback.feedback.expected_state.velocity.twist.angular.y, _x.action_feedback.feedback.expected_state.velocity.twist.angular.z))
      buff.write(self.action_feedback.feedback.expected_state.velocity.covariance.tostring())
      _x = self
      buff.write(_struct_7d.pack(_x.action_feedback.feedback.current_state.pose.pose.position.x, _x.action_feedback.feedback.current_state.pose.pose.position.y, _x.action_feedback.feedback.current_state.pose.pose.position.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.x, _x.action_feedback.feedback.current_state.pose.pose.orientation.y, _x.action_feedback.feedback.current_state.pose.pose.orientation.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.w))
      buff.write(self.action_feedback.feedback.current_state.pose.covariance.tostring())
      _x = self
      buff.write(_struct_6d.pack(_x.action_feedback.feedback.current_state.velocity.twist.linear.x, _x.action_feedback.feedback.current_state.velocity.twist.linear.y, _x.action_feedback.feedback.current_state.velocity.twist.linear.z, _x.action_feedback.feedback.current_state.velocity.twist.angular.x, _x.action_feedback.feedback.current_state.velocity.twist.angular.y, _x.action_feedback.feedback.current_state.velocity.twist.angular.z))
      buff.write(self.action_feedback.feedback.current_state.velocity.covariance.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.action_goal is None:
        self.action_goal = seabee3_actions.msg.FollowTrajectoryActionGoal()
      if self.action_result is None:
        self.action_result = seabee3_actions.msg.FollowTrajectoryActionResult()
      if self.action_feedback is None:
        self.action_feedback = seabee3_actions.msg.FollowTrajectoryActionFeedback()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.action_goal.header.seq, _x.action_goal.header.stamp.secs, _x.action_goal.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_goal.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_goal.goal_id.stamp.secs, _x.action_goal.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_goal.goal_id.id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.action_goal.goal.trajectory.header.seq, _x.action_goal.goal.trajectory.header.stamp.secs, _x.action_goal.goal.trajectory.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_goal.goal.trajectory.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.action_goal.goal.trajectory.intervals = []
      for i in range(0, length):
        val1 = seabee3_msgs.msg.TrajectoryInterval()
        _v43 = val1.length
        _x = _v43
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _struct_2i.unpack(str[start:end])
        _v44 = val1.initial_state
        _v45 = _v44.pose
        _v46 = _v45.pose
        _v47 = _v46.position
        _x = _v47
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v48 = _v46.orientation
        _x = _v48
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _struct_4d.unpack(str[start:end])
        start = end
        end += 288
        _v45.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
        _v49 = _v44.velocity
        _v50 = _v49.twist
        _v51 = _v50.linear
        _x = _v51
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v52 = _v50.angular
        _x = _v52
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        start = end
        end += 288
        _v49.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
        _v53 = val1.acceleration
        _v54 = _v53.twist
        _v55 = _v54.linear
        _x = _v55
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        _v56 = _v54.angular
        _x = _v56
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _struct_3d.unpack(str[start:end])
        start = end
        end += 288
        _v53.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
        self.action_goal.goal.trajectory.intervals.append(val1)
      _x = self
      start = end
      end += 12
      (_x.action_result.header.seq, _x.action_result.header.stamp.secs, _x.action_result.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_result.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_result.status.goal_id.stamp.secs, _x.action_result.status.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_result.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_result.status.status,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_result.status.text = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.action_result.result.final_waypoint.pose.pose.position.x, _x.action_result.result.final_waypoint.pose.pose.position.y, _x.action_result.result.final_waypoint.pose.pose.position.z, _x.action_result.result.final_waypoint.pose.pose.orientation.x, _x.action_result.result.final_waypoint.pose.pose.orientation.y, _x.action_result.result.final_waypoint.pose.pose.orientation.z, _x.action_result.result.final_waypoint.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_result.result.final_waypoint.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.action_result.result.final_waypoint.velocity.twist.linear.x, _x.action_result.result.final_waypoint.velocity.twist.linear.y, _x.action_result.result.final_waypoint.velocity.twist.linear.z, _x.action_result.result.final_waypoint.velocity.twist.angular.x, _x.action_result.result.final_waypoint.velocity.twist.angular.y, _x.action_result.result.final_waypoint.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_result.result.final_waypoint.velocity.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 12
      (_x.action_feedback.header.seq, _x.action_feedback.header.stamp.secs, _x.action_feedback.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_feedback.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.action_feedback.status.goal_id.stamp.secs, _x.action_feedback.status.goal_id.stamp.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_feedback.status.goal_id.id = str[start:end]
      start = end
      end += 1
      (self.action_feedback.status.status,) = _struct_B.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.action_feedback.status.text = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.action_feedback.feedback.target_interval.length.secs, _x.action_feedback.feedback.target_interval.length.nsecs, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.position.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.x, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.y, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.z, _x.action_feedback.feedback.target_interval.initial_state.pose.pose.orientation.w,) = _struct_2i7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.target_interval.initial_state.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.linear.z, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.x, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.y, _x.action_feedback.feedback.target_interval.initial_state.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.target_interval.initial_state.velocity.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.target_interval.acceleration.twist.linear.x, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.y, _x.action_feedback.feedback.target_interval.acceleration.twist.linear.z, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.x, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.y, _x.action_feedback.feedback.target_interval.acceleration.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.target_interval.acceleration.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 56
      (_x.action_feedback.feedback.expected_state.pose.pose.position.x, _x.action_feedback.feedback.expected_state.pose.pose.position.y, _x.action_feedback.feedback.expected_state.pose.pose.position.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.x, _x.action_feedback.feedback.expected_state.pose.pose.orientation.y, _x.action_feedback.feedback.expected_state.pose.pose.orientation.z, _x.action_feedback.feedback.expected_state.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.expected_state.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.expected_state.velocity.twist.linear.x, _x.action_feedback.feedback.expected_state.velocity.twist.linear.y, _x.action_feedback.feedback.expected_state.velocity.twist.linear.z, _x.action_feedback.feedback.expected_state.velocity.twist.angular.x, _x.action_feedback.feedback.expected_state.velocity.twist.angular.y, _x.action_feedback.feedback.expected_state.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.expected_state.velocity.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 56
      (_x.action_feedback.feedback.current_state.pose.pose.position.x, _x.action_feedback.feedback.current_state.pose.pose.position.y, _x.action_feedback.feedback.current_state.pose.pose.position.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.x, _x.action_feedback.feedback.current_state.pose.pose.orientation.y, _x.action_feedback.feedback.current_state.pose.pose.orientation.z, _x.action_feedback.feedback.current_state.pose.pose.orientation.w,) = _struct_7d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.current_state.pose.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      _x = self
      start = end
      end += 48
      (_x.action_feedback.feedback.current_state.velocity.twist.linear.x, _x.action_feedback.feedback.current_state.velocity.twist.linear.y, _x.action_feedback.feedback.current_state.velocity.twist.linear.z, _x.action_feedback.feedback.current_state.velocity.twist.angular.x, _x.action_feedback.feedback.current_state.velocity.twist.angular.y, _x.action_feedback.feedback.current_state.velocity.twist.angular.z,) = _struct_6d.unpack(str[start:end])
      start = end
      end += 288
      self.action_feedback.feedback.current_state.velocity.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=36)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_B = struct.Struct("<B")
_struct_6d = struct.Struct("<6d")
_struct_36d = struct.Struct("<36d")
_struct_2i = struct.Struct("<2i")
_struct_3I = struct.Struct("<3I")
_struct_7d = struct.Struct("<7d")
_struct_4d = struct.Struct("<4d")
_struct_2I = struct.Struct("<2I")
_struct_2i7d = struct.Struct("<2i7d")
_struct_3d = struct.Struct("<3d")
