"""autogenerated by genmsg_py from Imu.msg. Do not edit."""
import roslib.message
import struct

import geometry_msgs.msg

class Imu(roslib.message.Message):
  _md5sum = "9c6f91134201341f0f89439c6ff9ed57"
  _type = "seabee3_msgs/Imu"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 accel
geometry_msgs/Vector3 gyro
geometry_msgs/Vector3 mag
geometry_msgs/Vector3 ori

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['accel','gyro','mag','ori']
  _slot_types = ['geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       accel,gyro,mag,ori
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Imu, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.accel is None:
        self.accel = geometry_msgs.msg.Vector3()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Vector3()
      if self.mag is None:
        self.mag = geometry_msgs.msg.Vector3()
      if self.ori is None:
        self.ori = geometry_msgs.msg.Vector3()
    else:
      self.accel = geometry_msgs.msg.Vector3()
      self.gyro = geometry_msgs.msg.Vector3()
      self.mag = geometry_msgs.msg.Vector3()
      self.ori = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_12d.pack(_x.accel.x, _x.accel.y, _x.accel.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.mag.x, _x.mag.y, _x.mag.z, _x.ori.x, _x.ori.y, _x.ori.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.accel is None:
        self.accel = geometry_msgs.msg.Vector3()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Vector3()
      if self.mag is None:
        self.mag = geometry_msgs.msg.Vector3()
      if self.ori is None:
        self.ori = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.accel.x, _x.accel.y, _x.accel.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.mag.x, _x.mag.y, _x.mag.z, _x.ori.x, _x.ori.y, _x.ori.z,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_12d.pack(_x.accel.x, _x.accel.y, _x.accel.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.mag.x, _x.mag.y, _x.mag.z, _x.ori.x, _x.ori.y, _x.ori.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.accel is None:
        self.accel = geometry_msgs.msg.Vector3()
      if self.gyro is None:
        self.gyro = geometry_msgs.msg.Vector3()
      if self.mag is None:
        self.mag = geometry_msgs.msg.Vector3()
      if self.ori is None:
        self.ori = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.accel.x, _x.accel.y, _x.accel.z, _x.gyro.x, _x.gyro.y, _x.gyro.z, _x.mag.x, _x.mag.y, _x.mag.z, _x.ori.x, _x.ori.y, _x.ori.z,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_12d = struct.Struct("<12d")
